version: 2
updates:
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: daily
      time: "17:26"
      timezone: "Australia/Melbourne"
    open-pull-requests-limit: 10
    groups:
      boto3:
        patterns:
          - "*boto3*"
          - "botocore*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:37"
      timezone: "Australia/Melbourne"
    open-pull-requests-limit: 5